// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkq40JJL7d8Vcfliy5iC7wahMMekbxGo',
    appId: '1:513782611526:web:af341ba99e4b205d145447',
    messagingSenderId: '513782611526',
    projectId: 'rdp-todolist-6e1ca',
    authDomain: 'rdp-todolist-6e1ca.firebaseapp.com',
    storageBucket: 'rdp-todolist-6e1ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQU0Y5mgMOC3j7_TW2BcsGF04S1MZTX0',
    appId: '1:513782611526:android:cd37e2bcbe53d8c6145447',
    messagingSenderId: '513782611526',
    projectId: 'rdp-todolist-6e1ca',
    storageBucket: 'rdp-todolist-6e1ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKPKuhnSanF9FRLV_8TQx8iu9ZS2KEH4I',
    appId: '1:513782611526:ios:72da490245e488d0145447',
    messagingSenderId: '513782611526',
    projectId: 'rdp-todolist-6e1ca',
    storageBucket: 'rdp-todolist-6e1ca.firebasestorage.app',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKPKuhnSanF9FRLV_8TQx8iu9ZS2KEH4I',
    appId: '1:513782611526:ios:72da490245e488d0145447',
    messagingSenderId: '513782611526',
    projectId: 'rdp-todolist-6e1ca',
    storageBucket: 'rdp-todolist-6e1ca.firebasestorage.app',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqkq40JJL7d8Vcfliy5iC7wahMMekbxGo',
    appId: '1:513782611526:web:5126d306308e8c09145447',
    messagingSenderId: '513782611526',
    projectId: 'rdp-todolist-6e1ca',
    authDomain: 'rdp-todolist-6e1ca.firebaseapp.com',
    storageBucket: 'rdp-todolist-6e1ca.firebasestorage.app',
  );
}
